### ISSUE TITLE
Tagging specific entity in italian language: error in training the discriminative model.

### ISSUE THREAD

**Issue by v2-dev** [snorkel-team/snorkel#1094]
I would like to thank the whole research group for this amazing project! 
Recently I was assigned a project from my job in which I have to extract from a dataset a specific entity. This dataset is composed by a .txt documents of italian legal cases; the label and the entity I have to consider is the money involved in the case. This money can be in the form of numbers or literals like "5000 euro" or "cinquemila euro". What I want to do is to extract the sentence or the phrase that talk about money from my dataset to generate training data. Snorkel is perfect for this case! I saw your tutorials and some issues on github related to single entity extraction but I still have some perplexities.

This is the candidity extraction phase:
```python
ngrams         = Ngrams(n_max=7)
generic_matcher = NgramMatcher()
cand_extractor = CandidateExtractor(Quantity, [ngrams], [generic_matcher]) 
```
Do you suggest something else? Because like I said before the entity that I want to extract are in form of numbers and literals, representing the same thing.

About the labeling functions I have used this, but I think I am missing something like the return of the negative cases, am I right? Because I think that with only this labeling function my dataset is biased. Do you suggest some useful regex in this situation?

```python
patterns = {'€', 'EUR', 'Euro', 'Eur', 'euro', 'lira', 'lire', 'dollari', '£',
           'cento', 'diecimila','centomila','milione','milioni', 'miliardo', 'miliardi', 
            'importo', 'soldi'}

def LF_get_from_left(s):
    if len(patterns.intersection(get_left_tokens(s, window=2))) > 0:
        return 1
    else:
        return 0
    
def LF_get_from_right(s):
    if len(patterns.intersection(get_right_tokens(s, window=2))) > 0:
        return 1
    else:
        return 0
```
Finally, when I try to train the discriminative model I got some strange errors:

```python
from snorkel.learning.tensorflow.rnn import *
train_kwargs = {
    'lr':         0.001,
    'dim':        100,
    'n_epochs':   10,
    'dropout':    0.25,
    'print_freq': 1,
    'batch_size': 128,
    'max_sentence_length': 100
}

lstm = TagRNN(n_threads=None)
lstm.train(train_cands, train_marginals, X_dev=dev_cands, Y_dev=L_gold_dev, **train_kwargs)

ValueError: operands could not be broadcast together with shapes (32422,) (0,) 
```
Of course I'm missing something.

**Comment by v2-dev** [comment]
By the way I was wondering: what if I don't have hand labeled data for gold labels? Can I still ran the discriminative model?

**Comment by paroma** [comment]
For the labeling functions, you can try to come up with examples that will label an example as a negative (or abstain) like in the spouse tutorial. 

for the discriminative model, check if `train_cands` and `train_marginals` are both the same size. You can still train the discriminative model with labels from the generative model. You would need gold labels for the test set to *evaluate* how the discriminative model performs on the test set

**Comment by vincentschen** [comment]
Hi @v2-dev — thanks again for your questions: 

> Do you suggest something else? Because like I said before the entity that I want to extract are in form of numbers and literals, representing the same thing.

We don't have NER extraction built into the repo at the moment— we actually have a discussion on our forum tracking a potential [tutorial here](https://spectrum.chat/snorkel/tutorials/snorkel-tutorial-for-ner~34d56436-41e6-4216-a05b-59cf391a7fb3). Check that post out — maybe some of the resources could be helpful!

> About the labeling functions I have used this, but I think I am missing something like the return of the negative cases, am I right? Because I think that with only this labeling function my dataset is biased. Do you suggest some useful regex in this situation?

Indeed — adding negative cases would be useful to training a discriminative model. (Otherwise, there's no signal to learn a clear decision boundary!) The [spouses](https://github.com/snorkel-team/snorkel-tutorials/tree/master/spouse) tutorial might also be a good pointer for information extraction LFs more broadly.

> By the way I was wondering: what if I don't have hand labeled data for gold labels? Can I still ran the discriminative model?

Once you get it working, you should be able to use the output of `GenerativeModel` as training labels for the discriminative model!

As an FYI — we've moved the end-to-end info extraction application to https://github.com/snorkel-team/snorkel-extraction with the v0.9 release. 
Closing this issue for now; feel free to open any issues that project if you have any follow-up questions!
