### ISSUE TITLE
Adding optional arguments to nlp_labeling_function decorator

### ISSUE THREAD

**Issue by phosseini** [snorkel-team/snorkel#1425]
## Is your feature request related to a problem? Please describe.
In my classes, sometimes I need to pass optional arguments to those methods which are decorated with `nlp_labeling_function` and use `self` but I cannot do it now and I get the following error: `missing 1 required positional argument: 'x'` where `x` is the argument of the method decorated with `nlp_labeling_function` , correct me if I'm wrong.

## Describe the solution you'd like
Adding optional arguments to `nlp_labeling_function`

**Comment by vincentschen** [comment]
If you're trying to pass an additional arg to the underlying function, I'd recommend using [`resources`](https://snorkel.readthedocs.io/en/v0.9.0/packages/_autosummary/labeling/snorkel.labeling.labeling_function.html?highlight=resources#snorkel-labeling-labeling-function) in the decorator:
```
from snorkel.labeling import labeling_function

KEYWORDS = ["hello", "world"]

@labeling_function(resources=dict(keywords=KEYWORDS))
def f(x, keywords):
    return 1 if x.text in keywords else -1

from types import SimpleNamespace

x = SimpleNamespace(text="hello")
f(x) # 1
```

There's also an example of this in the [intro tutorial](https://www.snorkel.org/use-cases/01-spam-tutorial).

Otherwise, the decorated function `f` requires some data point `x`, which could contain different struct fields.
