### ISSUE TITLE
Function Zoo for some common applications.

### ISSUE THREAD

**Issue by mrbeann** [snorkel-team/snorkel#1493]
The LF is a fantastic idea, and it can be shared across different users, so I think a Function Zoo (similar to Model Zoo) will be very useful.

**Comment by eggie5** [comment]
That's a really good idea!

**Comment by dataframing** [comment]
I think if you'd like to contribute cross-domain utilities, maybe make a PR and add it under `snorkel/contrib`? Check out the README [here](https://github.com/snorkel-team/snorkel/tree/master/snorkel/contrib).

**Comment by bhancock8** [comment]
Thanks for opening this discussion! An LF Zoo is something we’ve been excited about for a while as well. It's on our roadmap, but we want to make sure it's done with proper organization, testing, etc. so that it remains clean, maintainable, and general. We would most likely host it in another repo, leaving the snorkel repo focused on the core functionality. We’ll be sure to post to the Snorkel [mailing list](https://groups.google.com/forum/#!forum/snorkel-ml) once we have anything to announce!

**Comment by mrbeann** [comment]
Yeah, this ZOO is more difficult to build and needs elaborate designs. Here are a few things I can come up with now, hope it can help.
1. The common task may define hierarchical.
2. A new repo with samples and contribution guidelines.
3. Some automate quality testing can be provided to test new PR.

Hope this can be build to make snorkel more practical. And feel free to close this issue.

**Comment by vincentschen** [comment]
Hi @mrbeann @eggie5 @dataframing — I wanted loop around to share some scaffolding for the snorkel-zoo that you all alluded to earlier: https://github.com/snorkel-team/snorkel-zoo

Feel free to open a PR contributions in this repo — excited to see what LFs you've had in mind!
