### ISSUE TITLE
Is there web interface for integrating SNORKEL?

### ISSUE THREAD

**Issue by strategist922** [snorkel-team/snorkel#1564]
Dear Developers,

Is there web interface for integrating SNORKEL? So that users can leverage 
Snorkel to do annotation by using browser?

Thanks and best regards,
James

**Comment by Vickzhang** [comment]
This would be very helpful.

**Comment by bhancock8** [comment]
Hi James, great question! The Snorkel open source project is currently just what you see here: a Python package that can be integrated into weak-supervision-based ML pipelines. But we're exploring other ways of interacting with the technology. To stay up-to-date on any new interfaces to Snorkel, you can join our [mailing list](https://groups.google.com/forum/#!forum/snorkel-ml) for occasional announcements or the [forum](https://spectrum.chat/snorkel?tab=posts) for discussion.

**Comment by ajratner** [comment]
To quickly add on: in production versions of Snorkel that have been deployed in industry and government, interfaces are certainly a big help and a critical part of the pipeline.  Generally these have to be customized per-application, data type, and setting--which is why we don't currently have them as part of the core Snorkel repo--and also require non-trivial engineering work; however to see examples that we've published about see snorkel.org!
