### ISSUE TITLE
LabelModel training is occupying a lot of memory.

### ISSUE THREAD

**Issue by sujeethrv** [snorkel-team/snorkel#1656]
I am trying to build a text classification model.

I have around 1200 labelling functions and 56 unique classes. When I train the Labelmodel by calling LabelModel.fit on my laptop(8GB memory) it is throwing kernel died on Jupyter notebook. When I run the same code from the jupyter notebook in a python script(.py file) the code is not throwing any error but there is no progress. The code throws the below warning and stops there.

warning - python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by humzaiqbal** [comment]
Hi sujeethrv,
In general, this research implementation of the LabelModel from the 2019 AAAI paper on Snorkel was intended for relatively low cardinality problems. As an alternative (with a lower compute and memory footprint), you could try using the MajorityLabelVoter class instead of the LabelModel for this problem.
