### ISSUE TITLE
How do we get coefficients for the interactions of 2 labeling functions?

### ISSUE THREAD

**Issue by datduong** [snorkel-team/snorkel#1682]
## Is your feature request related to a problem? Please describe.
Not a bug problem. I would like to know: where are the coefficients for the interactions of 2 labeling functions? For example, suppose we have 2 labeling functions L1 and L2. In the exponential term of the graphical model (from original paper here http://www.vldb.org/pvldb/vol11/p269-ratner.pdf), we fit w1 lambda(L1=y) + w2 lambda(L2=y) + w3 lambda(L1=L2), where w3 is the weight for the agreement of L1 and L2. How can I get this w3? 

I can only see a way to [get w1 and w2 here](https://github.com/snorkel-team/snorkel/blob/master/snorkel/labeling/model/label_model.py#L373)

## Describe the solution you'd like
I have no solution since I'm not an expert at Snorkel. 

## Describe alternatives you've considered
I have no solution since I'm not an expert at Snorkel. 

## Additional context
None

**Comment by humzaiqbal** [comment]
Hi datduong,

Those parameters (sometimes these are called the "canonical parameters") aren't computed explicitly because they're not necessary for computing P(Y|Lambda). That is we don't need them to obtain the probabilistic labels. Instead what are used are called the "mean" parameters, mu in the codebase. Both kinds of parameters are generally equivalent. For more on the types of parameters and their role in exponential models this book http://people.eecs.berkeley.edu/~wainwrig/Papers/WaiJor08_FTML.pdf may be useful.

Hope this helps!

**Comment by datduong** [comment]
Thanks.
