### ISSUE TITLE
Upgrade numpy from <=1.20.0 to 1.21.5 to support M1 Macs

### ISSUE THREAD

**Issue by rjurney** [snorkel-team/snorkel#1689]
## Is your feature request related to a problem? Please describe.

The numpy based stack grows ever taller. numpy 1.19 is 2 years old. We can't build Snorkel on an M1 Mac and other processors of that family because it does not support numpy 1.19.X. They require `1.21.4`, and the latest is `1.21.5`. M1s are now the only processors Apple is shipping, so Snorkel no longer supports Macs... which are a very popular development platform for Snorkel.

## Describe the solution you'd like

I want to upgrade the requirements.txt entry for numpy `<=1.20` to `<=1.21.5` so we can build snorkel on a Mac M1 processor.

## Describe alternatives you've considered

Abandon numpy, implement our own version. Seems like upgrading is better.

## Additional context

I do not understand the problem with numpy 1.2.0 and could use guidance in figuring this out so I can see if we can help perform this work at https://deepdiscovery.ai

https://numpy.org/devdocs/release/1.21.5-notes.html

**Comment by rsmith49** [comment]
Hi @rjurney! I’ve created PR #1690 to make the update. It looks like mypy checks [fail](https://app.circleci.com/pipelines/github/snorkel-team/snorkel/18/workflows/43ca2b97-f3e0-4e25-af0b-ba17b3d898b0/jobs/58) with the new numpy version, so if you would like to add to that PR with those fixes (or start your own PR) that would be awesome!

Otherwise, we will look into making these fixes in the next week or so and update you with our progress.

**Comment by zexuan-zhou** [comment]
Curious if there is any update on this or solution to this issue
