### ISSUE TITLE
Can I use  Snorkel for  multi-label problems ?

### ISSUE THREAD

**Issue by bpandey23** [snorkel-team/snorkel#1725]
I want to do a multi-label classification(14 labels) using snorkel , but when i am using MajorityLabelVoter it is giving me this error "IndexError: index 5 is out of bounds for axis 0 with size 2" .As per this issue  https://github.com/snorkel-team/snorkel/issues/1041 i have used the naive approach i.e treating each label as a separate binary classification problem but i am not satisfied with the end result. Can you please recommend best course of action here .

Thanks.

**Comment by bhancock8** [comment]
Hi @bpandey23, thank you for the question. Yes, multi-label problems are very common in the wild. This repo primarily contains the code for reproducing some of the early papers for the Snorkel research project, many of which were multi-class, but none of which were multi-label. Since forming Snorkel AI, we've done additional research and development to create multi-label compatible LF templates, label models, analysis tools, etc., and all of those are in Snorkel Flow, but none are backwards compatible with this library. So I don't have any open source implementations to point you to, unfortunately.

**Comment by bpandey23** [comment]
@bhancock8 , no problem . Thank for the update.
