### ISSUE TITLE
memory issue when parsing large corpus

### ISSUE THREAD

**Issue by nadavborenstein** [snorkel-team/snorkel#936]
Hi!

I am trying to run Snorkel on a corpus of Wikipedia articles (~27,000 articles, ~800,000 sentences), and I've encountered a problem while using the built-in parser to parse the corpus and save it in an SQL DB. When I use only ~20,000 articles everything runs smoothly, but when I use the entire 27,000 the system just freezes after a while and no progress is made, probably due to RAM shortage.

How can I bypass this problem? Adding more RAM is a bit problematic...

I'm running Snorkel inside a Linux VM, which has 11G of RAM, on a Windows machine with 16G RAM. 

Those are the specs of the VM:
![vm-specs](https://user-images.githubusercontent.com/15877500/40355295-b168e1ee-5dbe-11e8-86eb-81900e01e95e.PNG)

And the running freezes here (no progress is made after 98%):
![the freeze](https://user-images.githubusercontent.com/15877500/40355297-b1e460c6-5dbe-11e8-8a43-b0b04e99d37b.PNG)

**Comment by dolphin-zs** [comment]
I think current open sourced version of snorkel is not good at processing very large data.
An alternative approach may be dividing your corpus into several small csv files.
Remember to set `clear` argument of `apply()` function as False, then parsing and dumping into database one by one.

**Comment by pidugusundeep** [comment]
You can use something this to load multiple files below
```
from snorkel.parser import TextDocPreprocessor
parent="<folder directory>"
doc_preprocessor = TextDocPreprocessor(parent)
```

**Comment by nadavborenstein** [comment]
@dolphin-zs 
Whenever I try to add new data to the existing DB (by setting clear=False), I get the following Traceback.
Is there anything that I do wrong?

![exception](https://user-images.githubusercontent.com/15877500/40385380-12f2a35a-5e0f-11e8-95f6-cd119fce07a5.PNG)

**Comment by stephenbach** [comment]
Regarding original issue, it’s not clear that this is a memory or corpus size issue. When this has happened before, the culprit has been one document that is parsed as a single sentence causing subsequent steps like dependency parsing to take a really long time.

Some questions for debugging:
1) Is there any indication that the system is actually paging to disk?
2) What happens when you parse the remaining 8k docs? Can you identify specific docs that it’s freezing on?

Regarding your subsequent exception, the issue is that you’re trying to parse a document with the same name (‘0’) as one already in the database.

**Comment by dom-scio** [comment]
I faced the same issue and I absolutely needed to divide the documents in smaller size batches otherwise the RAM just went up too much before the sentences were flushed in the DB. Typically I create 20 batches which means calling 20 times corpus_parser.apply(). By doing this, a lot of transient objects are destroyed and the RAM stays quite low.

Regarding your exception, it looks you are re-parsing the same document in a subsequent batch. In my case I had to derive CSVPathsPreprocessor and instantiate a new doc_processor object with :

```
def _get_files(self, path):
        with codecs.open(path, encoding=self.encoding) as lines:
            for doc_path in list(lines)**[self.start:self.end]**:
                if self.column is not None:
                    # if column is set, retrieve specific column from CSV record
                    doc_path = doc_path.split(self.delim)[self.column]
                yield doc_path.strip()
```

where start and end are the indices to use in the document list.

**Comment by nadavborenstein** [comment]
@stephenbach 
regarding the questions:
1) Both the RAM and the disk usage are very high when it happens.
2) It works just fine on all of the remaining documents, there is no freeze.

And thank you very much! the exception was indeed resolved after I've made sure that all of the documents are unique.

**Comment by stephenbach** [comment]
Thanks everyone for the helpful info! My intuition was off here. Not sure why sentences are accumulated in memory before flushing to disk. I don't see anything obvious in the code that would cause this to happen.

I'll leave this issue open until we have a better solution, but sounds like everyone is using the workaround for now.

Note for finding a fix: perhaps there's some SQL Alchemy parameter that needs to be tuned?

**Comment by henryre** [comment]
Hi all, Snorkel v0.9 (this repo) has a lot more support for big data operations. Checkout our [Drybell example](https://github.com/snorkel-team/snorkel-tutorials/tree/master/drybell) for an example of using spaCy with Snorkel's Spark and Dask operators. As an FYI, we've moved the information extraction version of Snorkel (v0.7) to https://github.com/snorkel-team/snorkel-extraction.
